services:
  selenoid:
    container_name: selenoid
    image: "aerokube/selenoid:1.11.2"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD/config:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/video:/opt/selenoid/video/"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video
  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui:1.10.11"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
